services:
  - type: web
    plan: free
    name: UPLOADER-BOT-V3
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    repo: https://github.com/Siddwap/DRM-TXT-UPLOADER      
    branch: Master
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
    autoDeploy: false
