services:
  - type: web
    name: DRM Uploader bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/Siddwap/DRM-TXT-UPLOADER/
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: 2087326318:AAGRcDp10n62WWmjZN4njTKQXf5rVOKZbmg
      - key: API_ID
        sync: 8087060
      - key: API_HASH
        sync: ead24e1abe37e9a80b16ef0f468350b6
      - key: WEBHOOK
        sync: True
      - key: PORT
        sync: 5375  # Default port value, update if needed
